PrivateKey = {Path = "/etc/zkevm/dac.keystore", Password = "{{.keystore_password}}"}

[L1]
WsURL = "{{.l1_ws_url}}"
RpcURL = "{{.l1_rpc_url}}"
PolygonValidiumAddress = "{{.zkevm_rollup_address}}"
DataCommitteeAddress = "{{.polygon_data_committee_address}}"
Timeout = "1m"
RetryPeriod = "5s"
BlockBatchSize = "64"
GenesisBlock = "0"
TrackSequencer = false

[Log]
Level = "{{.log_level}}"
Outputs = ["stderr"]
Environment = "{{.environment}}"

[DB]
User = "{{.dac_db.user}}"
Password = "{{.dac_db.password}}"
Name = "{{.dac_db.name}}"
Host = "{{.dac_db.hostname}}"
Port = "{{.dac_db.port}}"
EnableLog = false
MaxConns = 200

[RPC]
Host = "0.0.0.0"
Port = {{.rpc_port_number}}
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 500