
endpoints:
  - name: L1
    executionUrl: "{{.l1_el_rpc_url}}"
    consensusUrl: "{{.l1_cl_rpc_url}}"

web:
  server:
    host: "0.0.0.0"
    port: "{{.server_port_number}}"
  frontend:
    enabled: true
    debug: true
    pprof: true
