PathRWData = "{{.zkevm_path_rw_data}}"
L1URL="{{.l1_rpc_url}}"
L2URL="{{.l2_rpc_url}}"
AggLayerURL="{{.agglayer_grpc_url}}"

NetworkID = {{.zkevm_rollup_id}}
SequencerPrivateKeyPath = "{{or .l2_sequencer_keystore_file "/etc/aggkit/sequencer.keystore"}}"
SequencerPrivateKeyPassword  = "{{.l2_keystore_password}}"

{{- if lt .aggkit_version "0.8" }}
polygonBridgeAddr = "{{.zkevm_bridge_address}}"
{{- end }}

RPCURL = "{{.l2_rpc_url}}"

# This values can be override directly from genesis.json
rollupCreationBlockNumber = "{{.rollup_manager_block_number}}"
rollupManagerCreationBlockNumber = "{{.rollup_manager_block_number}}"
genesisBlockNumber = "{{.rollup_manager_block_number}}"
[L1Config]
	URL = "{{.l1_rpc_url}}"
	chainId = "{{.l1_chain_id}}"
	polygonZkEVMGlobalExitRootAddress = "{{.zkevm_global_exit_root_address}}"
	polygonRollupManagerAddress = "{{.zkevm_rollup_manager_address}}"
	polTokenAddress = "{{.pol_token_address}}"
	polygonZkEVMAddress = "{{.rollup_address}}"

[L2Config]
	GlobalExitRootAddr = "{{.zkevm_global_exit_root_l2_address}}"

[Log]
Level = "{{.log_level}}"
Outputs = ["stderr"]
Environment = "{{.environment}}"

[REST]
Port = "{{.aggkit_node_rest_api_port}}"

[AggSender]
CertificateSendInterval = "1m"
CheckSettledInterval = "5s"

[ClaimSponsor]
DBPath = "{{.zkevm_path_rw_data}}/claimsponsor.sqlite"
Enabled = "{{.enable_aggkit_claim_sponsor}}"
SenderAddr = "{{.l2_claimsponsor_address}}"
BridgeAddrL2 = "{{.zkevm_bridge_l2_address}}"

[ClaimSponsor.EthTxManager]
PrivateKeys = [
    {Path = "/etc/aggkit/claimsponsor.keystore", Password = "{{.l2_keystore_password}}"},
]
StoragePath = "{{.zkevm_path_rw_data}}/ethtxmanager-claimsponsor.sqlite"

[ClaimSponsor.EthTxManager.Etherman]
URL = "{{.l2_rpc_url}}"
L1ChainID = "{{.zkevm_rollup_chain_id}}"
