# https://github.com/0xPolygonHermez/zkevm-node/blob/v0.5.13/test/config/test.node.config.toml
IsTrustedSequencer = false

[Log]
Environment = "production" # "production" or "development"
Level = "debug"
Outputs = ["stderr"]

[State]
        [State.DB]
        User = "{{.zkevm_db_state_user}}"
        Password = "{{.zkevm_db_state_password}}"
        Name = "state_db"
        Host = "{{.zkevm_db_state_hostname}}{{.deployment_suffix}}"
        Port = "{{.zkevm_db_postgres_port}}"
        EnableLog = false
        MaxConns = 200
        [State.Batch]
                [State.Batch.Constraints]
                MaxTxsPerBatch = 300
                MaxBatchBytesSize = 120000
                MaxCumulativeGasUsed = 1125899906842624
                MaxKeccakHashes = 2145
                MaxPoseidonHashes = 252357
                MaxPoseidonPaddings = 135191
                MaxMemAligns = 236585
                MaxArithmetics = 236585
                MaxBinaries = 473170
                MaxSteps = 7570538
                MaxSHA256Hashes = 1596

[Pool]
FreeClaimGasLimit = 1500000
IntervalToRefreshBlockedAddresses = "5m"
IntervalToRefreshGasPrices = "5s"
MaxTxBytesSize=100132
MaxTxDataBytesSize=100000
DefaultMinGasPriceAllowed = 1000000000
MinAllowedGasPriceInterval = "5m"
PollMinAllowedGasPriceInterval = "15s"
AccountQueue = 64
GlobalQueue = 1024
        [Pool.EffectiveGasPrice]
                Enabled = false
                L1GasPriceFactor = 0.25
                ByteGasCost = 16
                ZeroByteGasCost = 4
                NetProfit = 1
            BreakEvenFactor = 1.1
                FinalDeviationPct = 10
                EthTransferGasPrice = 0
                EthTransferL1GasPriceFactor = 0
                L2GasPriceSuggesterFactor = 0.5
        [Pool.DB]
        User = "{{.zkevm_db_pool_user}}"
        Password = "{{.zkevm_db_pool_password}}"
        Name = "pool_db"
        Host = "{{.zkevm_db_pool_hostname}}{{.deployment_suffix}}"
        Port = "{{.zkevm_db_postgres_port}}"
        EnableLog = false
        MaxConns = 200

[Etherman]
URL = "{{.l1_rpc_url}}"
ForkIDChunkSize = 20000
MultiGasProvider = false
        [Etherscan]
                ApiKey = ""

[RPC]
Host = "0.0.0.0"
Port = {{.zkevm_rpc_http_port}}
ReadTimeout = "60s"
WriteTimeout = "60s"
BatchRequestsEnabled = true
BatchRequestsLimit = 500
MaxRequestsPerIPAndSecond = 5000
SequencerNodeURI = "{{.trusted_sequencer_node_uri}}"
EnableL2SuggestedGasPricePolling = true
        [RPC.WebSockets]
                Enabled = true
                Port = {{.zkevm_rpc_ws_port}}

[Synchronizer]
SyncInterval = "1s"
SyncChunkSize = 100
TrustedSequencerURL = "" # If it is empty or not specified, then the value is read from the smc.
L1SynchronizationMode = "sequential"
        [Synchronizer.L1ParallelSynchronization]
                MaxClients = 10
                MaxPendingNoProcessedBlocks = 25
                RequestLastBlockPeriod = "5s"
                RequestLastBlockTimeout = "5s"
                RequestLastBlockMaxRetries = 3
                StatisticsPeriod = "5m"
                TimeoutMainLoop = "5m"
                RollupInfoRetriesSpacing= "5s"
                FallbackToSequentialModeOnSynchronized = false
                [Synchronizer.L1ParallelSynchronization.PerformanceWarning]
                        AceptableInacctivityTime = "5s"
                        ApplyAfterNumRollupReceived = 10

[EthTxManager]
ForcedGas = 0

[L2GasPriceSuggester]
Type = "default"
UpdatePeriod = "10s"
Factor = 0.5
DefaultGasPriceWei = 1000000000
MaxGasPriceWei = 0

[MTClient]
URI  = "zkevm-executor{{.deployment_suffix}}:{{.zkevm_hash_db_port}}"

[Executor]
URI = "zkevm-executor{{.deployment_suffix}}:{{.zkevm_executor_port}}"
MaxGRPCMessageSize = 100000000

[Metrics]
Host = "0.0.0.0"
Port = {{.zkevm_prometheus_port}}
Enabled = true
ProfilingHost = "0.0.0.0"
ProfilingPort = {{.zkevm_pprof_port}}
ProfilingEnabled = true

[EventLog]
        [EventLog.DB]
        User = "{{.zkevm_db_event_user}}"
        Password = "{{.zkevm_db_event_password}}"
        Name = "event_db"
        Host = "{{.zkevm_db_event_hostname}}{{.deployment_suffix}}"
        Port = "{{.zkevm_db_postgres_port}}"
        EnableLog = true
        MaxConns = 200

[HashDB]
User = "{{.zkevm_db_executor_user}}"
Password = "{{.zkevm_db_executor_password}}"
Name = "executor_db"
Host = "{{.zkevm_db_executor_hostname}}{{.deployment_suffix}}"
Port = "{{.zkevm_db_postgres_port}}"
EnableLog = false
MaxConns = 200